name: blurhash_shader
description: "Implements BlurHash to create visually appealing low-resolution image placeholders using shaders for faster rendering."
version: 1.1.0
homepage: https://github.com/xioxin/blurhash_shader
repository: https://github.com/xioxin/blurhash_shader
issue_tracker: https://github.com/xioxin/blurhash_shader/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  shaders:
    - shaders/blurhash_64.frag

funding:
  - https://ko-fi.com/xioxin

topics:
  - ui
  - widget
  - blurhash
  - shader
  - placeholder